<?php

namespace App\Modules\Admin\Database\Seeds;

use App\Modules\Admin\Models\CategoryGroup;
use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('categories')->delete();

        \DB::table('categories')->insert(array(
            0 =>
                array(
                    'id' => 6,
                    'pid' => 0,
                    'category_group_id' => 1,
                    'name' => 'xitongpeizhi',
                    'nickname' => '系统配置',
                    'flag' => '',
                    'image' => 'layui-icon layui-icon-set',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "", "router": ""}',
                    'created_at' => '2020-04-27 14:27:42',
                    'updated_at' => '2020-04-27 14:27:42',
                    'deleted_at' => NULL,

                    'top_id' => 0,
                    'path' => NULL,
                    'level' => 1,
                ),
            1 =>
                array(
                    'id' => 7,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'basics',
                    'nickname' => '基础配置',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "", "router": "admin.settings.index"}',
                    'created_at' => NULL,
                    'updated_at' => '2020-04-27 14:27:42',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            2 =>
                array(
                    'id' => 8,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'menu',
                    'nickname' => '目录配置',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "?type=menu", "router": "admin.categories.index"}',
                    'created_at' => NULL,
                    'updated_at' => '2020-04-27 14:27:42',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            3 =>
                array(
                    'id' => 25,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'role',
                    'nickname' => '角色管理',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "", "router": "admin.roles.index"}',
                    'created_at' => NULL,
                    'updated_at' => '2020-04-27 14:27:42',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            4 =>
                array(
                    'id' => 26,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'permission',
                    'nickname' => '权限管理',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "", "router": "admin.permissions.index"}',
                    'created_at' => NULL,
                    'updated_at' => '2020-04-27 14:27:42',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            5 =>
                array(
                    'id' => 53,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'users',
                    'nickname' => '用户管理',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "", "router": "admin.users.index"}',
                    'created_at' => NULL,
                    'updated_at' => '2020-04-27 14:27:42',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            6 =>
                array(
                    'id' => 54,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'front_column',
                    'nickname' => '前端栏目管理',
                    'flag' => '',
                    'image' => NULL,
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "?type=front_column", "router": "admin.categories.index"}',
                    'created_at' => '2020-04-28 15:50:24',
                    'updated_at' => '2020-04-28 15:50:24',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            7 =>
                array(
                    'id' => 55,
                    'pid' => 0,
                    'category_group_id' => 2,
                    'name' => 'design',
                    'nickname' => '设计文章',
                    'flag' => '',
                    'image' => 'layui-icon layui-icon-home',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"show": "1", "home_top": "0"}',
                    'created_at' => '2020-04-28 15:56:54',
                    'updated_at' => '2020-05-11 14:21:12',
                    'deleted_at' => NULL,

                    'top_id' => 0,
                    'path' => NULL,
                    'level' => 1,
                ),
            8 =>
                array(
                    'id' => 56,
                    'pid' => 55,
                    'category_group_id' => 2,
                    'name' => 'web',
                    'nickname' => '网页',
                    'flag' => '',
                    'image' => 'layui-icon layui-icon-auz',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 10,
                    'status' => '1',
                    'value' => '{"show": "1", "home_top": "0"}',
                    'created_at' => '2020-04-28 15:57:12',
                    'updated_at' => '2020-05-11 14:21:22',
                    'deleted_at' => NULL,

                    'top_id' => 55,
                    'path' => '55',
                    'level' => 2,
                ),
            9 =>
                array(
                    'id' => 57,
                    'pid' => 55,
                    'category_group_id' => 2,
                    'name' => 'ui',
                    'nickname' => 'UI',
                    'flag' => '',
                    'image' => 'layui-icon layui-icon-rate-half',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 9,
                    'status' => '1',
                    'value' => '{"show": "1", "home_top": "1"}',
                    'created_at' => '2020-04-28 15:57:31',
                    'updated_at' => '2020-05-11 14:21:28',
                    'deleted_at' => NULL,

                    'top_id' => 55,
                    'path' => '55',
                    'level' => 2,
                ),
            10 =>
                array(
                    'id' => 58,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'article_source',
                    'nickname' => '文章来源',
                    'flag' => '',
                    'image' => NULL,
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "?type=article_source", "router": "admin.categories.index"}',
                    'created_at' => '2020-04-28 16:40:23',
                    'updated_at' => '2020-04-28 16:40:23',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            11 =>
                array(
                    'id' => 59,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'article',
                    'nickname' => '文章分类',
                    'flag' => '',
                    'image' => NULL,
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "?type=article", "router": "admin.categories.index"}',
                    'created_at' => '2020-04-28 16:40:52',
                    'updated_at' => '2020-04-28 16:40:52',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            12 =>
                array(
                    'id' => 60,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'tag',
                    'nickname' => '标签管理',
                    'flag' => '',
                    'image' => NULL,
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "?type=tag", "router": "admin.categories.index"}',
                    'created_at' => '2020-04-28 16:41:24',
                    'updated_at' => '2020-04-28 16:42:29',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            13 =>
                array(
                    'id' => 61,
                    'pid' => 0,
                    'category_group_id' => 5,
                    'name' => 'article_tag',
                    'nickname' => '文章标签',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => NULL,
                    'created_at' => '2020-04-28 16:53:14',
                    'updated_at' => '2020-04-28 16:53:14',
                    'deleted_at' => NULL,

                    'top_id' => 0,
                    'path' => NULL,
                    'level' => 1,
                ),
            16 =>
                array(
                    'id' => 64,
                    'pid' => 0,
                    'category_group_id' => 4,
                    'name' => 'test_aa',
                    'nickname' => '分类一',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => NULL,
                    'created_at' => '2020-04-28 16:54:08',
                    'updated_at' => '2020-04-28 16:54:08',
                    'deleted_at' => NULL,

                    'top_id' => 0,
                    'path' => NULL,
                    'level' => 1,
                ),
            17 =>
                array(
                    'id' => 65,
                    'pid' => 0,
                    'category_group_id' => 3,
                    'name' => 'source',
                    'nickname' => '来源一',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => NULL,
                    'created_at' => '2020-04-28 16:57:44',
                    'updated_at' => '2020-04-28 16:57:44',
                    'deleted_at' => NULL,

                    'top_id' => 0,
                    'path' => NULL,
                    'level' => 1,
                ),
            18 =>
                array(
                    'id' => 66,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'article_index',
                    'nickname' => '文章管理',
                    'flag' => '',
                    'image' => NULL,
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": null, "router": "admin.articles.index"}',
                    'created_at' => '2020-04-28 17:36:25',
                    'updated_at' => '2020-04-28 17:36:25',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            19 =>
                array(
                    'id' => 67,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'slides',
                    'nickname' => '轮播图设置',
                    'flag' => '',
                    'image' => NULL,
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": null, "router": "admin.slides.index"}',
                    'created_at' => '2020-05-07 14:13:21',
                    'updated_at' => '2020-05-07 14:13:21',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => '6',
                    'level' => 2,
                ),
            21 =>
                array(
                    'id' => 69,
                    'pid' => 6,
                    'category_group_id' => 1,
                    'name' => 'slides_group',
                    'nickname' => '轮播图分组',
                    'flag' => '',
                    'image' => NULL,
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"param": "?type=slides", "router": "admin.categories.index"}',
                    'created_at' => '2020-05-08 13:49:34',
                    'updated_at' => '2020-05-08 13:49:34',
                    'deleted_at' => NULL,

                    'top_id' => 6,
                    'path' => NULL,
                    'level' => 2,
                ),
            23 =>
                array(
                    'id' => 71,
                    'pid' => 0,
                    'category_group_id' => 6,
                    'name' => 'home',
                    'nickname' => 'home',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"column_id": null, "column2_id": null}',
                    'created_at' => '2020-05-11 11:07:10',
                    'updated_at' => '2020-05-11 11:07:10',
                    'deleted_at' => NULL,

                    'top_id' => 0,
                    'path' => NULL,
                    'level' => 1,
                ),
            24 =>
                array(
                    'id' => 72,
                    'pid' => 0,
                    'category_group_id' => 6,
                    'name' => 'home_advertisement',
                    'nickname' => '首页广告位',
                    'flag' => '',
                    'image' => '',
                    'keywords' => '',
                    'description' => '',
                    'weigh' => 0,
                    'status' => '1',
                    'value' => '{"column_id": null, "column2_id": null}',
                    'created_at' => '2020-05-11 13:42:26',
                    'updated_at' => '2020-05-11 13:42:26',
                    'deleted_at' => NULL,

                    'top_id' => 0,
                    'path' => NULL,
                    'level' => 1,
                )
        ));
    }
}
